# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-2wKHnm9NtIM46LB69OlNKoTEjE1LUX
"""

import streamlit as st
import pandas as pd
import pickle

# Load model
model = pickle.load(open("model.pkl", "rb"))

st.title("📊 Sales Prediction App")
st.write("Predict sales based on your ad spend.")

tv = st.number_input("TV Ad Spend", 0.0, 500.0, 100.0)
radio = st.number_input("Radio Ad Spend", 0.0, 50.0, 20.0)
newspaper = st.number_input("Newspaper Ad Spend", 0.0, 50.0, 10.0)

if st.button("Predict Sales"):
    pred = model.predict([[tv, radio, newspaper]])
    st.success(f"Predicted Sales: {pred[0]:.2f} units")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import pickle
import numpy as np

# Create a dummy model for demonstration
class DummyModel:
    def predict(self, data):
        # Return a fixed value for demonstration
        return np.array([100.0])

dummy_model = DummyModel()

# Save the dummy model to a pickle file
with open("model.pkl", "wb") as f:
    pickle.dump(dummy_model, f)

print("Dummy model 'model.pkl' created.")